custom_cleaning:
  name: Custom Cleaning
  description: Zone Cleaning service call specific to Vorwerk Kobolds.
  fields:
    entity_id:
      name: "Vacuum Entity"
      description: "Name of the vacuum entity."
      example: "vacuum.my_vr"
      required: true
    mode:
      name: "Cleaning Mode"
      description: "Set the cleaning mode: 'eco' or 'turbo' (default)."
      default: turbo
      example: turbo
      selector:
        select:
          options:
            - turbo
            - eco
    navigation:
      name: "Navigation Mode"
      description: "Set the navigation mode: 'normal' (default) 'extra_care' or 'deep'."
      default: normal
      example: normal
      selector:
        select:
          options:
            - normal
            - extra_care
            - deep
    category:
      name: Category
      description: "Whether to use a persistent map or not for cleaning (i.e. no-go lines): 'map' (default) or 'no_map' (fallback, if no map exists)."
      default: map
      example: map
      advanced: true
      selector:
        select:
          options:
            - map
            - no_map
    zone:
      name: Zone
      description: "Name of the zone to clean. Defaults to no zone i.e. complete floor cleanup. Only supported by the VR300."
      example: "Kitchen"
      selector:
        text:
